void file_initialize();
void save_file(short mode);
void load_file();
void leave_town();
int do_waterfall(int flag);
int init_data(int flag);
void get_reg_data();
void build_data_file(short mode);
void reg_alert();
void remove_party_from_scen();
